data:
  input_path: data/reviews.csv
  test_size: 0.2


paths:
  plots_dir: outputs/plots
  log_dir: logs
  hf_output_dir: outputs/bert
  eval_output_dir: outputs/evaluation

logging:
  version: 1
  formatters:
    default:
      format: "%(asctime)s [%(levelname)s] %(name)s: %(message)s"
      datefmt: "%Y-%m-%d %H:%M:%S"
  handlers:
    console:
      class: logging.StreamHandler
      formatter: default
      level: INFO
    file:
      class: logging.FileHandler
      filename: logs/pipeline.log
      formatter: default
      level: DEBUG
  root:
    handlers: [console, file]
    level: DEBUG
  loggers:
    transformers:
      level: WARNING

seed: 42

traditional:
  models: ["logreg","lsvc","nb"]
  cv_folds: 5
  tfidf_max_df: [0.75, 1.0]
  logreg_C: [0.1,1.0]
  lsvc_C: [0.5,1.0]
  nb_alpha: [0.5,1.0]

bert:
  tokenizer:
    model_name: "bert-base-uncased"
    max_length: 128
  training_params:
    epochs: 3
    learning_rate: 2e-5
    per_device_train_batch_size: 16
    per_device_eval_batch_size: 16
    weight_decay: 0.01
    fp16: true
  output_dir: outputs/bert

evaluation:
  label_mapping:
    labels: [0, 1]
    target_names: ["negative", "positive"]